#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <stdlib.h>
#include <sys/wait.h>
#include <string.h>

/*
  Write a program that creates 5 child processes. Connect all 6 processes with a “ring” topology through pipes: the
  parent process will be connected to child 1, child 1 is connected to child 2, ..., and child 5 is connected to the parent
  process. The goal is to find the greatest random number generated by all processes:

  a)Each process generates a random number between 1 and 500. Then, it prints it along with its PID;

  b)Then, the parent process sends its generated number to child 1;

  c)Child 1 compares the parent’s number with its own random number and sends the greater of the two to child 2;

  d)All other processes follow the same behavior, until child 5 sends the greater number to the parent process;

  e)The parent process prints the greatest random number.
*/

int rand_num(int min, int max){
    srand(time(NULL));
    return rand() % (max - min) + min;
}

int main(){

    int fd[6][2]; // File Descriptor 2D array for the 6 pipes.

    int gen_num=0, rec_num=0; // Generated Number and Received Number

    for(int i=0;i<5;i++){
        if(pipe(fd[i]) < 0){
            perror("Failed creating pipe!");
            return 1;
        }
    }

    for(int i=0;i<5;i++){
        if(fork() == 0){

            gen_num = rand_num(1, 500) + i;
            printf("\nPID[%d]|NUM[%d]\n", getpid(), gen_num);

            read(fd[i][0], &rec_num, sizeof(int));

            printf("\nIs %d > %d ?\n", gen_num, rec_num);
            close(fd[i][0]);
            //printf("\nEu, filho %d recebi: %d\n", i, rec_num);

            int greatest = (rec_num > gen_num) ? rec_num : gen_num;
            write(fd[i+1][1], &greatest, sizeof(int));
            close(fd[i+1][1]);
            exit(1);
        }
    }

    gen_num = rand_num(1, 500);
    printf("\nParent generated: %d\n", gen_num);
    write(fd[0][1], &gen_num, sizeof(int));
    //printf("\nEu, pai enviei: %d\n", gen_num);
    close(fd[0][1]);
    read(fd[5][0], &rec_num, sizeof(int));
    close(fd[5][0]);

    printf("\nGreatest number generated: %d\n", rec_num);

    return 0;
}